### ISSUE TITLE
Enable gh pages

### ISSUE THREAD

**Issue by annakrystalli** [markdunning/orda-dataviz#1]
Hi @markdunning,

any chance you could enable gh pages for this repo?

**Comment by markdunning** [comment]
The master branch has been set to serve gh-pages. Edit index.md and the webpage for the repository will appear as if by magic at:-

https://markdunning.github.io/orda-dataviz/

:tada: 

(I selected the "minimal" theme, but feel free to change in the _config.yml file)

**Comment by annakrystalli** [comment]
👏👏👏🎉
